import plugin from 'tailwindcss/plugin';

export default {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  safelist: ['animate-spin'],
  theme: {
    colors: {
      current: 'currentColor',
      transparent: 'transparent',
      white: 'rgb(var(--white) / <alpha-value>)',
      black: 'rgb(var(--black) / <alpha-value>)',
      brand: 'rgb(var(--brand) / <alpha-value>)',
      brand_alt: 'rgb(var(--brand_alt) / <alpha-value>)',
      up: 'rgb(var(--up) / <alpha-value>)',
      down: 'rgb(var(--down) / <alpha-value>)',
      success: 'rgb(var(--success) / <alpha-value>)',
      error: 'rgb(var(--error) / <alpha-value>)',
      warn: 'rgb(var(--warn) / <alpha-value>)',
      warning_brighter: 'rgb(var(--warning_brighter) / <alpha-value>)',
    },
    fontFamily: {
      primary: [
        'avertastd-mono',
        'Poppins',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
    },
    fontWeight: {
      400: 400,
      500: 500,
      600: 600,
      700: 700,
      800: 800,
    },
    fontSize: {
      0: 0,
      9: '9px',
      10: '10px',
      11: '11px',
      12: '12px',
      13: '13px',
      14: '14px',
      15: '15px',
      16: '16px',
      18: '18px',
      20: '20px',
      21: '21px',
      22: '22px',
      24: '24px',
      26: '26px',
      28: '28px',
      30: '30px',
      32: '32px',
      36: '36px',
      38: '38px',
      44: '44px',
      50: '50px',
    },
    borderRadius: {
      none: '0px',
      DEFAULT: '4px',
      full: '9999px',
      1.5: '6px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
    },
    borderSpacing: {
      none: 0,
      md: '4px',
    },
    screens: {},
    lineHeight: {
      none: '1',
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      9: '36px',
      10: '40px',
    },
    spacing: {
      px: '1px',
      0: '0',
      0.5: '2px',
      1: '4px',
      1.5: '6px',
      2: '8px',
      2.5: '10px',
      3: '12px',
      3.5: '14px',
      4: '16px',
      4.5: '18px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      9: '36px',
      10: '40px',
      11: '44px',
      12: '48px',
      13: '52px',
      14: '56px',
      15: '60px',
      16: '64px',
      17: '68px',
      18: '72px',
      19: '76px',
      20: '80px',
      21: '84px',
      22: '88px',
      24: '96px',
      25: '100px',
      26: '104px',
      28: '112px',
      30: '120px',
      32: '128px',
      34: '136px',
      36: '144px',
      40: '160px',
      44: '176px',
      48: '192px',
      50: '200px',
      52: '208px',
      56: '224px',
      60: '240px',
      64: '256px',
      72: '288px',
      80: '320px',
      96: '384px',
      100: '400px',
    },
    flexGrow: {
      DEFAULT: '1',
      0: '0',
      2: '2',
      3: '3',
      max: '10000',
    },
    extend: {
      boxShadow: {
        normal: '0px 4px 24px 0px rgba(0, 0, 0, 0.2)',
        t: '0px -4px 24px 0px rgba(0, 0, 0, 0.2)',
        r: '4px 0px 24px 0px rgba(0, 0, 0, 0.2)',
        l: '-4px 0px 24px 0px rgba(0, 0, 0, 0.2)',
        b: '0px 4px 24px 0px rgba(0, 0, 0, 0.2)',
      },
      backgroundColor: {
        primary: 'var(--bg-primary)', // 待删除
        secondary: 'var(--bg-secondary)', // 待删除
        layer1: 'var(--bg-layer1)',
        layer2: 'var(--bg-layer2)',
        layer3: 'var(--bg-layer3)',
        layer4: 'var(--bg-layer4)',
        layer5: 'var(--bg-layer5)',
        layer6: 'var(--bg-layer6)',
        layer7: 'var(--bg-layer7)',
        layer8: 'var(--bg-layer8)',
        tab_selected: 'var(--bg-tab_selected)',
        alpha5: 'var(--bg-alpha5)',
        alpha10: 'var(--bg-alpha10)',
        inherit: 'inherit',
        colorful1: 'var(--colorful1)',
        colorful4: 'var(--colorful4)',
        colorful5: 'var(--colorful5)',
        colorful6: 'var(--colorful6)',
        colorful7: 'var(--colorful7)',
        colorful8: 'var(--colorful8)',
        colorful9: 'var(--colorful9)',
        colorful10: 'var(--colorful10)',
        colorful12: 'var(--colorful12)'
      },
      fill: {
        layer2: 'var(--bg-layer2)',
        layer3: 'var(--bg-layer3)',
        layer4: 'var(--bg-layer4)',
        layer5: 'var(--bg-layer5)',
        layer6: 'var(--bg-layer6)',
        layer7: 'var(--bg-layer7)',
        colorful1: 'var(--colorful1)',
      },
      textColor: {
        primary: 'rgb(var(--text-primary) / <alpha-value>)',
        primary_brand: 'var(--text-primary_brand)',
        secondary: 'var(--text-secondary)',
        tertiary: 'var(--text-tertiary)',
        quarterary: 'var(--text-quarterary)',
        layer5: 'var(--bg-layer5)',
      },
      borderColor: {
        layer1: 'var(--bg-layer1)',
        layer2: 'var(--bg-layer2)',
        layer3: 'var(--bg-layer3)',
        layer4: 'var(--bg-layer4)',
        layer5: 'var(--bg-layer5)',
        layer6: 'var(--bg-layer6)',
        main: 'var(--border-main)',
        second: 'var(--border-second)',
        thirdly: 'var(--border-thirdly)',
        input: 'var(--border-input)',
        selected: 'var(--selected)',
        colorful4: 'var(--colorful4)',
        colorful5: 'var(--colorful5)',
        colorful6: 'var(--colorful6)',
        colorful7: 'var(--colorful7)',
        colorful8: 'var(--colorful8)',
        colorful9: 'var(--colorful9)',
        colorful10: 'var(--colorful10)',
      },
      stroke: {
        main: 'var(--border-main)',
        thirdly: 'var(--border-thirdly)',
        input: 'var(--border-input)',
      },
      maxWidth: () => ({
        none: 'none',
        screen: '100vw',
        full: '100%',
        min: 'min-content',
        max: 'max-content',
        fit: 'fit-content',
      }),
      flexGrow: {
        '2': '2',
      },
      minHeight: ({ theme }) => ({ ...theme('spacing') }),
      zIndex: {
        max: 99999999,
        modal: 999999,
        ['modal-up']: 1000000,
        ['modal-down']: 999998,
      },
      gradientColorStops: {
        colorful4: 'var(--colorful4)',
        colorful5: 'var(--colorful5)',
        colorful6: 'var(--colorful6)',
        colorful7: 'var(--colorful7)',
        colorful8: 'var(--colorful8)',
        colorful9: 'var(--colorful9)',
        colorful10: 'var(--colorful10)',
        layer3: 'var(--bg-layer3)',
      },
    },
  },
  variants: {
    stroke: ['hover', 'focus'],
  },
  plugins: [
    plugin(({ matchUtilities, theme }) => {
      matchUtilities(
        {
          'col-min': (value) => ({
            gridTemplateColumns: `repeat(auto-fit, minmax(${value}, 1fr))`,
          }),
        },
        { values: theme('spacing') }
      );
    }),
    plugin(({ addVariant }) => {
      // 校正三方响应式
      ['s768', 's1024', 's1366', 's1440', 's1920'].forEach((key) => addVariant(key, `.detrade.${key} &`));
      addVariant('light', '.detrade-light &');
      // 去除移动端hover效果
      addVariant('hover', '@media(min-width: 768px){&:hover}');
      addVariant('group-hover', '@media(min-width: 768px){.group:hover &}');
    }),
    plugin(function ({ addUtilities }) {
      // 这里定义的功能类可以被编辑器插件识别, index.css里定义的不能
      addUtilities({
        '.hoverable': {
          '@apply hover:brightness-105': '',
          '@apply light:hover:brightness-95': '',
        },
        '.flex-center': {
          display: 'flex',
          'align-items': 'center',
          'justify-content': 'center',
        },
        '.abs-center': {
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate3D(-50%, -50%, 0)',
        },
        '.no-scrollbar': {
          '-ms-overflow-style': 'none',
          'scrollbar-width': 'none',
          '&::-webkit-scrollbar': {
            display: 'none',
          },
        },
        '.darkness': {
          'background-image': 'linear-gradient(0deg,rgba(255, 255, 255, 0.03) 0%,rgba(255, 255, 255, 0.03) 100%)',
          '.detrade-light &': {
            'background-image': 'linear-gradient(0deg,rgba(0, 0, 0, 0.03) 0%,rgba(0, 0, 0, 0.03) 100%)',
          },
        },
        '.text-9': {
          'font-size': '10px',
          transform: 'scale(0.9)',
        },
      });
    }),
  ],
};
